import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Button, Link } from '@mui/material'
import StyledLink from '@/components/StyleComponents/StyledLink'
import CurrentDate from '@/components/StyleComponents/CuttentDate'
import ImageText from '@/components/StyleComponents/ImageText'
import BodySection from '@/components/indexpagelayout/BodySection'
import LoginButton from '@/components/StyleComponents/LogInButton/LogInButton'
import { useRouter } from "next/router";


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter();
  const moveToLoginPage=(e: React.MouseEvent<HTMLButtonElement>)=>{
    e.preventDefault();
    router.push("/login");
  }
  return (
    <>
      <Head>
        <title>City Group Apps</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
      
        <div className={styles.description}>
        {/* <CurrentDate></CurrentDate> */}
          {/* <p>
            Welcome to City Group Apps&nbsp;
            {/* <code className={styles.code}>src/pages/index.tsx</code> }
          </p> */}
          <p>
            
          <ImageText imageUrl="/logo2.png"
        imageAlt="Logo"
        text="Welcome to City Group Apps" textColor="Black"></ImageText>
          

          </p>
          
         
        </div>

        <div className={styles.description}>
        <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
              
            >
              Powered By : <span style={{'color':'crimson', fontWeight:'Bold',fontSize:'1.5rem'}}>IT, City Group</span>
            </a>
          </div>
          {/* <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          /> */}
          {/* <div className={styles.thirteen}>
            <p>Welcome to City group Apps</p>
            
          </div> */}
          {/*  */}

          
        </div>
       
       <BodySection>
           <br/>
           <LoginButton onClickEvent={moveToLoginPage} />
           <br/>
       </BodySection>

        {/* */}

        <div className={styles.grid}>
        <StyledLink href="/services" underlineHoverColor="red">
       
          <div
            className={styles.card}
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Our Services <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </div>
          </StyledLink>
        
        <StyledLink href="/about" underlineHoverColor="red">
          <div
            className={styles.card}
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              About Us <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </div>
          </StyledLink>  
          <StyledLink href="/contact" underlineHoverColor="red">
          <div
            className={styles.card}
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Contact Us <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </div>
          </StyledLink> 

          {/* <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a> */}
        </div>
      </main>
    </>
  )
}
